pipeline {
  agent {
    kubernetes {
      cloud 'terralogic-eks-agent'
      namespace 'cloudbees-builds'
      inheritFrom 'jenkins-kaniko-agent'
      defaultContainer 'jnlp'
    }
  }

  options {
    skipDefaultCheckout true
    disableConcurrentBuilds()
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }

  environment {
    MAVEN_REPO     = 'maven-repo'
    MVN_CACHE_NAME = 'mvn-cache'
  }

  stages {

    /* ================= SCM CHECKOUT ================= */
    stage('Checkout') {
      steps {
        echo "Checkout → repo=${repoUrl}, branch=${branchName}, creds=${gitCredentials}"

        checkout([
          $class: 'GitSCM',
          branches: [[name: "${branchName}"]],
          doGenerateSubmoduleConfigurations: false,
          extensions: [],
          submoduleCfg: [],
          userRemoteConfigs: [[
            url: "${repoUrl}",
            credentialsId: "${gitCredentials}"
          ]]
        ])
      }
    }

    /* ================= RESTORE MAVEN CACHE ================= */
    stage('Restore Maven Cache') {
      steps {
        sh "mkdir -p ${MAVEN_REPO}"
        readCache name: "${MVN_CACHE_NAME}"
      }
    }

    /* ================= MAVEN CLEAN BUILD ================= */
    stage('Maven Clean Build') {
      steps {
        sh """
          mvn clean install \
            -Dmaven.repo.local=${MAVEN_REPO}
        """
      }
    }

    /* ================= SAVE MAVEN CACHE ================= */
    stage('Save Maven Cache') {
      steps {
        writeCache(
          name: "${MVN_CACHE_NAME}",
          includes: "${MAVEN_REPO}/**"
        )
      }
    }
  }

  post {
    always {
      echo "Build completed: #${BUILD_NUMBER}"
      deleteDir()
    }
  }
}
